### ISSUE TITLE
How this library is different from alternatives.

### ISSUE THREAD

**Issue by husayt** [gioboa/vite-module-federation#2]
Hi, 
thank you for your efforts with this library. Module federation with vite is going to be really powerful mix. Yet there are a number of parallel effort going on in this space, which is very good. Here are some I know of:

- https://github.com/originjs/vite-plugin-federation
- https://github.com/dilesoft/vite-plugin-federation-dynamic
- https://github.com/fgsreally/vite-federation
- https://github.com/padcom/vite-plugin-federation

I wonder what would be the major difference of this library from the above. Would appreciate for your insight on this. Thanks

**Comment by gioboa** [comment]
Hi, I don't want to criticise other libraries, it's not in my character.
However two are custom implementations and the other two are a wrapper and a fork of one of the two custom libraries

The plus of this plugin is that is based on top of standard implementation and configuration, thanks to @softarc/native-federation apis. So switching from Webpack to Vite can be quite easy.
The implementation under the hood is rock solid because is based on the official implementation with years of testing.
Speaking with the official native-federation team they had also thought of moving this repo under their organisation.
